kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: worker
  extraPortMappings:
  - containerPort: 30000 # for Istio
    hostPort: 80
    listenAddress: "127.0.0.1"
    protocol: TCP
- role: worker
  extraPortMappings:
  - containerPort: 30000 # for Istio
    hostPort: 80
    listenAddress: "127.0.0.1"
    protocol: TCP
- role: worker
  extraPortMappings:
  - containerPort: 30000 # for Istio
    hostPort: 80
    listenAddress: "127.0.0.1"
    protocol: TCP