kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30000
    hostPort: 80
    listenAddress: "127.0.0.1"
    protocol: TCP
  - containerPort: 30001
    hostPort: 30001
    listenAddress: "127.0.0.1"
    protocol: TCP
  - containerPort: 30002
    hostPort: 30002
    listenAddress: "127.0.0.1"
    protocol: TCP
  extraMounts:
    - hostPath: ./frontend/src
      containerPath: /volumes/frontend/src
    - hostPath: ./mysql/datas/member  # developer's local directory
      containerPath: /volumes/mysql/member # not deployed application's container, but container KIND cluster is spinning up in
    - hostPath: ./golang/cmd
      containerPath: /volumes/golang/cmd
    - hostPath: ./jenkins/volume
      containerPath: /volumes/jenkins/volume
    - hostPath: ./wsl.conf
      containerPath: /etc/wsl.conf

# 1. string modifier like sed cannot be used in kubectl edit
# 2. tried to remove istio-ingressgateway service and re-create, but the pods has random string name, so cannot make it as a script
# 3. decide to install istio as a full plain yaml file w/ istioctl profile dump / istioctl manifest generate