apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-frontend
  labels:
    type: local
spec:
  storageClassName: ""
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /volumes/frontend/src
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mysql-member
  labels:
    type: local
spec:
  storageClassName: ""
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /volumes/mysql/member
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mysql-space
  labels:
    type: local
spec:
  storageClassName: ""
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /volumes/mysql/space
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-golang
  labels:
    type: local
spec:
  storageClassName: ""
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /volumes/golang/cmd
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-golang2
  labels:
    type: local
spec:
  storageClassName: ""
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /volumes/golang2/cmd
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-jenkins
  labels:
    type: local
spec:
  storageClassName: ""
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /volumes/jenkins/volume
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-member
  labels:
    type: local
spec:
  storageClassName: ""
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /volumes/member/src
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-rabbitmq
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: rabbitmq-storageclass
  hostPath:
    path: /volumes/rabbitmq
---