apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-frontend
  labels:
    type: local
spec:
  storageClassName: ""
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /volumes/frontend/src
---
