apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-frontend
  namespace: default
spec:
  resources:
    requests:
      storage: 8Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: pv-frontend
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mysql-member
  namespace: default
spec:
  resources:
    requests:
      storage: 8Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: pv-mysql-member
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mysql-space
  namespace: default
spec:
  resources:
    requests:
      storage: 8Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: pv-mysql-space
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-golang
  namespace: default
spec:
  resources:
    requests:
      storage: 8Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: pv-golang
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-golang2
  namespace: default
spec:
  resources:
    requests:
      storage: 8Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: pv-golang2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-member
spec:
  resources:
    requests:
      storage: 8Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: pv-member
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: rabbitmq-storageclass
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---