apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-frontend
  namespace: default
spec:
  resources:
    requests:
      storage: 8Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: pv-frontend
---