apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmqcluster
spec:
  replicas: 1
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 1
      memory: 2Gi
  rabbitmq:
          additionalConfig: |
                  log.console.level = info
                  channel_max = 1000
                  default_user= guest 
                  default_pass = guest
                  default_user_tags.administrator = true
  service:
    type: NodePort
  override:
    service:
      spec:
        ports:
        - appProtocol: http
          name: management
          nodePort: 30003
          port: 15672
          protocol: TCP
          targetPort: 15672
  persistence:
    storageClassName: rabbitmq-storageclass
    storage: 5Gi