apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-frontend
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-golang
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-golang2
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-member
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-mysql-member
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-mysql-space
---