FROM ubuntu/mysql:8.0-22.04_beta

USER nobody

COPY ./my.cnf ./etc/mysql/my.cnf

COPY ./scripts/member.sql /docker-entrypoint-initdb.d/member.sql

ENV MYSQL_ROOT_PASSWORD=1234
ENV MYSQL_DATABASE=memberdb
ENV MYSQL_ALLOW_EMPTY_PASSWORD=no